### ISSUE TITLE
how to enable live demo

### ISSUE THREAD

**Issue by tradysun** [reu2018DL/YOLO-LITE#4]
I open the live demo trained on VOC (https://reu2018dl.github.io/model_voc.html). But only real time video is showed and no predicted bbox result. Do I need do any configuration?

**Comment by rachuang22** [comment]
You need to point it at an object it is able to detect (bottle, person, etc)

**Comment by tradysun** [comment]
I also tried COCO model demo, and put person or bottle in the camera view. But no prediction bbox showing.

**Comment by Jped** [comment]
Hey
are you getting any bounding boxes at all? 
The tensorflow javascript library does not support every browser so if you are having issues try a different browser, computer, or try it on your cell phone.

**Comment by tradysun** [comment]
Thanks. Safari on cell phone is ok, but does not work for gooogle browser and ie browser on my laptop.
