### ISSUE TITLE
Where is coco weights?

### ISSUE THREAD

**Issue by aliyasineser** [reu2018DL/YOLO-LITE#5]
I am trying to use the coco cfg and weights. But I think cfg and weights folders for voc, not coco. And for coco there is only one cfg and no weights? Can anyone explain it for me?
Thanks

**Comment by rachuang22** [comment]
Just added, sorry about that.

**Comment by aliyasineser** [comment]
Thank you for the weights! No need to be sorry, I am glad you are supporting open source in a good way! Congratz for the project, I will make a reference if I manage to use it in my own project. 
Great day!
