### ISSUE TITLE
New models

### ISSUE THREAD

**Issue by Favi0** [reu2018DL/YOLO-LITE#7]
Hello @rachuang22 and @Jped first of all congratulations for the paper, very enjoyable read.

I would like to ask you how did you get the weights for each architecture? 

for example , if i want to remove one of the two 128 filter layers in your trial 3 NB to compare performance , what should i do with the weights? should i still use the original weights you provide and retrain my model? or should i retrain from scratch with random initialized weights for that architecture or what?

how was your process for getting weights for each try? 
i dont understand how one can get a pair of untrained weights with darknet framework

**Comment by Jped** [comment]
If you would like to remove one of the layers, you do not need to use any of the weights. Train from scratch, it wont take that long.

If you do not pass in any weights with darknet it will create its own.

**Comment by Favi0** [comment]
will try thanks

**Comment by Favi0** [comment]
what if i want to change the image resolution from one your baseline models? should i also retrain with voc/coco?

**Comment by rachuang22** [comment]
if you would like to change the image resolution you will still need to retrain the model. Hope this helps.
