### ISSUE TITLE
./src/parser.c:360: parse_region: Assertion `l.outputs == params.inputs' failed.

### ISSUE THREAD

**Issue by Dantetheash** [reu2018DL/YOLO-LITE#8]
I have my own dataset and I was trying to train Yolo-Lite on that dataset. I followed the instructions on how to train Yolo v2 on custom objects but when I start training this error comes up.

 ./darknet detector train cfg/obj.data cfg/yoloc.cfg 
yoloc
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   224 x 224 x   3   ->   224 x 224 x  16  0.043 BFLOPs
    1 max          2 x 2 / 2   224 x 224 x  16   ->   112 x 112 x  16
    2 conv     32  3 x 3 / 1   112 x 112 x  16   ->   112 x 112 x  32  0.116 BFLOPs
    3 max          2 x 2 / 2   112 x 112 x  32   ->    56 x  56 x  32
    4 conv     64  3 x 3 / 1    56 x  56 x  32   ->    56 x  56 x  64  0.116 BFLOPs
    5 max          2 x 2 / 2    56 x  56 x  64   ->    28 x  28 x  64
    6 conv    128  3 x 3 / 1    28 x  28 x  64   ->    28 x  28 x 128  0.116 BFLOPs
    7 max          2 x 2 / 2    28 x  28 x 128   ->    14 x  14 x 128
    8 conv     35  3 x 3 / 1    14 x  14 x 128   ->    14 x  14 x  35  0.016 BFLOPs
    9 max          2 x 2 / 2    14 x  14 x  35   ->     7 x   7 x  35
   10 conv    256  3 x 3 / 1     7 x   7 x  35   ->     7 x   7 x 256  0.008 BFLOPs
   11 conv    425  1 x 1 / 1     7 x   7 x 256   ->     7 x   7 x 425  0.011 BFLOPs
   12 detection
darknet: ./src/parser.c:360: parse_region: Assertion `l.outputs == params.inputs' failed.
Aborted (core dumped)

**Comment by Jped** [comment]
Hi 
I am not sure exactly what is happening here, maybe you can look at the [darknet github page](https://github.com/pjreddie/darknet).

**Comment by Dantetheash** [comment]
Okay, I found the problem,
it was from my parameters in the cfg file 
my filter number was wrong
