### ISSUE TITLE
why best voc weight link does not point to the file？

### ISSUE THREAD

**Issue by zhen8838** [reu2018DL/YOLO-LITE#9]
hi! 

I want to find the best voc cfg and weight, but it seem the link does not point to the file？ can you help me ?
```md
[best PASCAL cfg](https://github.com/reu2018DL/yolo-lite) |  [best PASCAL weights](https://github.com/reu2018DL/yolo-lite)
```

**Comment by rachuang22** [comment]
Hello, we forgot to update the links. My apologies. 
The best voc cfg link: https://raw.githubusercontent.com/reu2018DL/YOLO-LITE/master/cfg/tiny-yolov2-trial3-noBatch.cfg
voc weight link: https://github.com/reu2018DL/YOLO-LITE/blob/master/weights/tiny-yolov2-trial3-noBatch.weights

Let me know if you have any issues.
